### ISSUE TITLE
Not able to build the sample on Azure Pipelines (maui-check issue)

### ISSUE THREAD

**Issue by anaselhajjaji** [dotnet/maui-samples#180]
I have the error below:

![image](https://user-images.githubusercontent.com/3309485/125675175-ecb948c6-18a0-429f-9b1a-474cb45bdfc2.png)

**Comment by jonathanpeppers** [comment]
The issue seems like the `maui-check` tool is not installed, we have an example here:

https://github.com/dotnet/maui-samples/blob/0937533818b2eae0a9d9d78b2638561480773731/azure-pipelines.yml#L32-L34

So the issue seems to be: "How do I install a [.NET global tool](https://docs.microsoft.com/dotnet/core/tools/global-tools) and run it?"

You can file future issues with `maui-check` here, thanks: https://github.com/Redth/dotnet-maui-check

**Comment by anaselhajjaji** [comment]
Maybe I was not clear...
Actually it's the https://github.com/dotnet/maui-samples/blob/main/azure-pipelines.yml
That I'm running on Azure DevOps. I just connected a fork of maui-samples repo to Azure Devops to be able to use the pipelines. And I got that error.

**Comment by jonathanpeppers** [comment]
See: https://github.com/dotnet/maui-samples/pull/181
