### ISSUE TITLE
CollectionViewDemos Scrolling Pages don't scroll on Windows or Android

### ISSUE THREAD

**Issue by bmclane** [dotnet/maui-samples#301]
According to this issue, should use a Grid instead of StackLayout
https://github.com/dotnet/maui/issues/8990

https://github.com/dotnet/maui-samples/blob/fb630d735facd5929fab6b4f7410477b32f872ff/6.0/UserInterface/Views/CollectionViewDemos/CollectionViewDemos/Views/Scrolling/ScrollToByIndexPage.xaml

**Comment by iSeiryu** [comment]
I replaced `<StackLayout Margin="20">` with `<Grid Margin="20">` and the vertical scroll started working.
This also worked:
```xml
<ScrollView>
    <VerticalStackLayout Margin="10">
        <CollectionView ItemsSource="{Binding Animals}"
        ...
        </CollectionView>
    </VerticalStackLayout>
</ScrollView>
```

Which way is proper/better?

**Comment by bebenlebricolo** [comment]
Hi, I could reproduce the same behaviors with the latest revision (commit ac29ad78259df288d16e4126424bb52f86203dda) of the samples.
I'm testing on a android device (Xiaomi Mi Note 10 lite) and wrapping in Grids instead of StackLayouts seems to do the trick.

However, scrolling is very choppy and this is the behavior I'm also having in an another app(...)
I know @davidbritch worked on that part of the code some time ago, I bet it's a matter of priorities.

@iSeiryu, I found in many places that having a CollectionView within a ScrollView is generally not advised, because it can be confusing for the user (essentially, that's what you'll find on the web and stackoverflow).
There might also be issues with sizing as well, so I'll tend to the first approach : replacing every StackLayout and derivatives by Grids.
By the way, it seems to be the trend with dotnet MAUI to deprecate StackLayouts in favor of Grids instead (and they are a bit more complex to use)
