### ISSUE TITLE
Add F# Sample ?

### ISSUE THREAD

**Issue by delneg** [dotnet/maui-samples#88]
Currently, all the samples are only for C#. Can we see some F# samples ?

**Comment by bddckr** [comment]
Adding a bit to this issue because I think it fits:

I have a Xamarin.Android and Xamarin.Mac project and would be interested to learn whether .NET 6 brings the awesome improvements to F# projects as well. F# Xamarin projects currently still use the old project system, there are [issues with a type provider in Android projects](https://github.com/xamarin/Xamarin.Android.FSharp.ResourceProvider/issues/9) and [`PackageReference` isn't supported](https://github.com/dotnet/fsharp/pull/5853).

I'm really looking forward to proper SDK-style projects and getting back to the same tech C# projects enjoy. Is that a goal with .NET 6?

**Comment by delneg** [comment]
Decided to take matters into my own hands and added a PR with iOS F# Sample.
